---
title: "Teaching"
---

## Federal University of São Carlos

```{r echo = FALSE}
courses = c("[Probability C](2018-prob_c.html)",
            "Decision Theory",
            "Classifical Inference",
            "Bayesian Inference",
            "Bayesian Inference",
            "Probability A",
            "Probability C",
            "Bayesian Inference",
            "Introduction to Statistical Planning")

years = c(2018,
          2017,
          2017,
          2017,
          2017,
          2016,
          2016,
          2016,
          2016
)

GG = "Graduate"
UU = "Undergraduate"
level = c(GG,
          UU,
          UU,
          UU,
          GG,
          UU,
          UU,
          UU,
          UU
)

courses_table = tibble::tibble(course=courses,
                               level=level,
                               year=years)
knitr::kable(courses_table)
```

## Carnegie Mellon University

```{r echo = FALSE}
courses = c("Introduction to Probability and Random Processes",
            "Introduction to Probability and Random Processes")
years = c(2014, 2013)
UU = "Undergraduate"
levels = c(UU, UU)
courses_table = tibble::tibble(course=courses, 
                               level=levels,
                               year=years)
knitr::kable(courses_table)
```
