---
title: "Aula 6 - Introdução ao Planejamento de Experimentos"
author: "Rafael Izbicki e Rafael Bassi Stern"
date: ''
bibliography: ipaee.bib
output: html_document
---

Nesta aula estudamos os conceitos de
**validade** e **eficácia** de experimentos.
Também vimos como 
a **aleatorização** e
o **controle** de variáveis podem
ser usados para obter
um experimento válido e eficaz.
Para tal, acompanhamos
o capítulo 5 de [@Diggle2011].

# Exercícios

1. Um grande grupo de comunicação de determinado país está
   interessado em estudar o grau de conhecimento de
   estudantes da principal universidade do país a respeito de
   notícias recentes de interesse geral.
   Em particular, um dos interesses é avaliar se
   estudantes formandos tem maior conhecimento médio de
   notícias recentes de interesse geral do que estudantes ingressantes.
   Para isso, para cada curso de graduação da universidade,
   o grupo selecionou aleatoriamente um aluno ingressante e
   um aluno formando e aplicou um teste de conhecimento de
   notícias recentes de interesse geral. Considere que
   essa universidade possui 71 cursos de graduação.
   Defina validade e eficácia de um planejamento amostral e
   indique quais medidas neste estudo foram tomadas para
   garantir cada uma destas propriedades. 

2. Um professor elabora 2 provas e
   deseja determinar se ambas são 
   igualmente difíceis.
   Para tal, selecionará
   uma amostra de 50 alunos dentre
   uma população de alunos habilitados
   para testar as provas.
   Como estas provas são demoradas,
   cada aluno só poderá realizar uma das provas.
   Exemplifique algumas técnicas que
   podem ser adotadas para obter 
   um planejamento válido e eficaz.

3. Uma pesquisador desenvolver um novo medicamento
   para tratar pacientes com doença de Parkinson.
   O pesquisador deseja realizar um experimento
   para testar o quão bem este medicamento
   se compara a um concorrente.
   Para tal tomará como amostra
   50 pacientes que se tratam com um determinado médico.
   O pesquisador determina que o médico
   poderá escolher metade destes para
   ser tratada com o novo medicamente e
   outra metade para ser tratada com o concorrente.
   Discuta a validade deste experimento.

4. Em um jogo de "par ou ímpar" você pode
   escolher entre o número 1,
   o número 2 ou jogar uma moeda
   e jogar 1 se sair cara e
   jogar 2 se sair coroa.
   Considere que seu oponente é capaz
   de descobrir qual das 3 opções
   você escolheu antes de
   determinar o lance dele.
   Neste contexto, qual a melhor alternativa disponível?
   Qual conexão existe entre este jogo e
   a importância de aleatorização para obter 
   a validade de um experimento?

# Referências
