---
sidemenu: "true"
title: "Research"
---

### Journal papers

```{r echo = FALSE, message = FALSE, warning = FALSE}
`%>%` = magrittr::`%>%`
paper_table = readr::read_csv("tables/papers_journal.csv") %>%
  dplyr::mutate(title = paste0("<a href='",
                               url,
                               "' target='_blank'>",
                               title,
                               "</a>"),
                preprint = paste0("<a href='",
                               preprint_url,
                               "' target='_blank'>",
                               preprint_name,
                               "</a>"),
                preprint = ifelse(is.na(preprint_name), "", preprint),
                journal = paste0("<b>", journal, "</b>")) %>%
  dplyr::arrange(desc(year)) %>% 
  dplyr::select(title, journal, preprint, field)
DT::datatable(paper_table,
              escape = FALSE,
              options = list(pageLength = 5, dom = 'ftip'),
              rownames = FALSE)
```

<br/>

### Papers in Conference Proceedings

```{r echo = FALSE, message = FALSE, warning = FALSE}
`%>%` = magrittr::`%>%`
paper_table = readr::read_csv("tables/papers_conference.csv") %>% 
  dplyr::mutate(title = paste0("<a href='",
                               url,
                               "' target='_blank'>",
                               title,
                               "</a>"),
                proceedings = paste0("<b>", proceedings, "</b>")) %>% 
   dplyr::select(-url)
DT::datatable(paper_table,
              escape = FALSE,
              
              options = list(dom = 't'),
              rownames = FALSE)
```

