---
title: "Jurimetrics in the Constitution"
author: "Rafael Bassi Stern"
date: 2018-04-23
categories: ["jurimetrics"]
tags: ["jurimetrics", "constitution", "habeas corpus", "presumption of innocence"]
---

I recently wrote a 
[text](https://abj.org.br/principios-conflitantes-e-jurimetria/) 
in portuguese which studies how Brazil's Supreme Federal Court 
decided ex-president Lula's *habeas corpus*.
In the following, I translate this text to English.

------

Brazil's Supreme Federal Court recently 
[decided](http://www.stf.jus.br/portal/cms/verNoticiaDetalhe.asp?idConteudo=374437) 
ex-president's Lula *habeas corpus* in a tight vote of
5 for and 6 against. In such a situation, 
some controversy is unavoidable.
One of the less sophisticated arguments is that
there exists a single valid interpretation of the Constitution and,
therefore, anyone who decides in the opposite direction is ill-intentioned.
This text aims to show that such personal arguments cannot
address the complex questions which were discussed in Lula's trial.

The first step is to prove that 
interpreting the Constitution is
a complex activity, which 
involves simultaneously considering several issues.
Indeed, Brazil's [Federal Constitution](http://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm) 
has 250 articles.
If all of these articles were interpreted intuitively and in isolation,
contradictions would immediately ensue.
For example, in the following I translate articles of the Constitution that
defend the right to privacy and also public security:

- Art. 5o, X: The intimacy, private life, honor and image of 
people are inviolable (...)
- Art. 144: Public security is a duty of the State and 
right and responsibility of every person (...)

If the right to privacy were interpreted 
in isolation and with maximum comprehensiveness, then
every type of security camera would be prohibited.
Similarly, if public security were interpreted 
in isolation and with maximum comprehensiveness, then
one would find a justification for an all-powerful State that
spies on every action of its citizens.
Contrary to these naive interpretations, 
most people conclude that there exists
a balance between these articles.
There is a middle term between security and privacy that
is more beneficial than either of the naive interpretations.
However, finding such a middle term is a complex and subjective question,
which can be answered in many ways.

In Lula's trial, a similar question motivated the
differences between the Ministers of the Supreme Court.
Each Minister defended a different balance between
articles of the Constitution.
One of these articles is translated below:

- Art. 5o, LVII: No one is guilty before
the final disposal of a criminal conviction.

The right which is protected in the passage above is 
called **presumption of innocence**. 
In Brazil, it is possible to
appeal of a criminal conviction several times.
If one interprets the presumption of innocence
in isolation and with maximum comprehensiveness, then
punishment would only be possible after
no new appeal is possible.

However, the Constitution also protects
several other rights, 
some of which are translated below:

- Art. 5o: (…) The State guarantees to Brazilians and foreigners living in Brazil
the inviolability of the right to their lives, liberty, equality, security and private property.
- Art. 5o, LXXVIII: The reasonable duration of trials is protected (...)
a todos (…) são assegurados a razoável duração do processo (…)

There exist a large number of appeals available in Brazil and 
Courts have long waiting lines for judging these appeals.
Hence, it is possible to argue that, if the State were to wait
until all appeals were judged before punishing the defendant, then
punishment would take so long that it would be almost equivalent 
to no punishment at all.
In this case, public security would be damaged,
since it depends partially on proper punishment.

The vote of each Minister searched for a different balance
between the constitutional principles described above.
Each position is justifiable, since such a harmonization
involves a subjective judgement of the relative importance of
each of the principles in each practical situation.
Another interesting point is that, with few exceptions,
the Ministers tend to vote consistently in favor of 
the same harmonization of principles.
That is, they vote according to their convictions and
not according to the defendant.

However, despite the validity of their votes,
it can be hard to understand exactly how each Minister
develops the balance of constitutional principles.
How different would have to be the facts so that
their votes would change?
This is a hard question because, in order to balance,
it is necessary to measure.
How much time must a trial take so that punishment is not efficient?
How much time does it take to decide each available appeal?
After what appeal is the trial so long that it compromises public security?
Although there still exists no single valid answer to these questions,
by answering them, the judge makes even more transparent
the rationale of his decision.
By combining Statistics to the Law,
Jurimetrics provides a new valuable tool
for accomplishing this goal.
In next posts, I plan to discuss some jurimetric arguments that
were presented by the Ministers in this case.
